import React from 'react';
import { motion } from 'motion/react';
import { ArrowLeft, Shield } from 'lucide-react';

interface LegalPageProps {
  onBack: () => void;
}

const TermsOfService = ({ onBack }: LegalPageProps) => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <button 
        onClick={onBack}
        className="mb-8 flex items-center gap-2 font-black uppercase text-sm hover:text-neo-pink transition-colors"
      >
        <ArrowLeft size={16} />
        BACK_TO_CORE
      </button>

      <div className="bg-white border-4 border-neo-black p-10 neo-shadow-lg notebook-bg relative overflow-hidden">
        <div className="flex items-center gap-4 mb-8 border-b-4 border-neo-black pb-4">
          <Shield className="text-neo-cyan" size={40} />
          <h1 className="text-5xl font-black tracking-tighter uppercase">Terms of Service</h1>
        </div>

        <div className="space-y-6 font-bold text-zinc-800 leading-relaxed">
          <section>
            <h2 className="text-xl font-black border-b-2 border-neo-black pb-1 mb-2">1. ACCEPTANCE OF TERMS</h2>
            <p>By accessing SOLOSCRIBE, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the system.</p>
          </section>

          <section>
            <h2 className="text-xl font-black border-b-2 border-neo-black pb-1 mb-2">2. USER RESPONSIBILITIES</h2>
            <p>Users are responsible for maintaining the confidentiality of their founder core credentials. All strategic output generated by the Inklo Engine is the sole responsibility of the user.</p>
          </section>

          <section>
            <h2 className="text-xl font-black border-b-2 border-neo-black pb-1 mb-2">3. INTELLECTUAL PROPERTY</h2>
            <p>Your strategy is sovereign. SoloScribe claims no ownership over the content you feed into or generate with the Inklo Engine.</p>
          </section>

          <section>
            <h2 className="text-xl font-black border-b-2 border-neo-black pb-1 mb-2">4. LIMITATION OF LIABILITY</h2>
            <p>SoloScribe and the Inklo Intelligence engine are provided "AS IS". We do not guarantee market success or specific financial outcomes based on AI-generated strategy.</p>
          </section>
        </div>

        {/* Notebook Holes Decoration */}
        <div className="absolute left-0 top-0 bottom-0 w-8 flex flex-col justify-around py-8 pointer-events-none">
           {[...Array(12)].map((_, i) => (
             <div key={i} className="w-3 h-3 rounded-full bg-[#f0f0f0] border-2 border-neo-black mx-auto" />
           ))}
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
